# Welcome to Lysande!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# The share_image is the image used when the site is linked to uing the OpenGraph-protocol.
# If rss is set to true an rss feed will be generated for the projects on your site.
title: your name - portfolio
email: example@gmail.com
description: This is a splendid website about me.
url: "https://theuggla.github.io/example" # the base hostname & protocol for your site
author: Arthur Dent
share_image: default.png
background_image: default_rustic.jpg
rss: true

# Usernames. If names are given here, an icon will appear with a link to than account in the site header.
disqus_shortname:
twitter_username:
github_username:
tumblr_username:
instagram_username:
facebook_username:
youtube_username:
pinterest_username:
youtube_channel: 
skype_inviteURL:
linkedin_usernameURL:
upwork_userID:

# Jekyll build settings
markdown: kramdown
permalink: pretty
baseurl: ""
exclude: 
   - Gemfile
   - Gemfile.lock
   - lysande.gemspec
   - README.md
plugins: 
   - jekyll-seo-tag

# Change the categories of projects to match yours!
# Collections
collections:
  projects:
    categories: [code, design, published]

# Front Matter Defaults
defaults:
  -
     scope:
        path: ""
     values:
        layout: "default"
  -
     scope:
        path: "_posts"
        type: "posts"
     values:
        layout: "post"
   -
     scope:
        path: "_projects"
        type: "projects"
     values:
        layout: "project"


