# Welcome to Lysande!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: your name - portfolio
email: example@gmail.com
description: > This is a splendid website about me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Arthur Dent
image: defaultprofile.png
rss: true

#usernames
disqus_shortname:
twitter_username:
github_username:
tumblr_username:
instagram_username:
facebook_username:
youtube_username:
pinterest_username:

# Build settings
markdown: kramdown
theme: lysande

# Change the categories of projects to match yours!
# Collections
collections:
  projects:
    categories: [code, design, publish]

# Defaults
defaults:
  -
     scope:
        path: ""
     values:
        layout: "default"
  -
     scope:
        path: ""
        type: "posts"
     values:
        layout: "post"


